name: Build My Webpage
#Part Demo, part build the page. Hopefully all working.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install NPM Dependencies
        run: npm ci

      - name: Compile the TypeScript code
        run: 
          npx tsc
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
      #Figure out how to deploy to GitHub Pages.
      